service: socio-computing-experiment

provider:
  name: aws
  runtime: python3.8
  
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParameters
        - ssm:GetParameter
      Resource: "arn:aws:ssm:*:*:parameter/*"
    - Effect: Allow
      Action:
        - ssm:DescribeParameters
      Resource: "*"

functions:
  data-collector:
    handler: handler.dataCollector
    events:
      - schedule: rate(2 hours)

resources: 
  Resources:
    tweetsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: tweet_info
        AttributeDefinitions:
          - AttributeName: tweet_id
            AttributeType: S
        KeySchema:
          - AttributeName: tweet_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5